module.exports = {
    Events: [
        "applicationCommandCreate",
        "applicationCommandDelete",
        "applicationCommandUpdate",
        "channelCreate",
        "channelDelete",
        "channelPinsUpdate",
        "channelUpdate",
        "debug",
        "emojiCreate",
        "emojiDelete",
        "emojiUpdate",
        "error",
        "guildBanAdd",
        "guildBanRemove",
        "guildCreate",
        "guildDelete",
        "guildIntegrationsUpdate",
        "guildMemberAdd",
        "guildMemberAvailable",
        'guildMemberRemove',
        'guildMembersChunk',
        'guildMemberUpdate',
        'guildUnavailable',
        'guildUpdate',
        'interaction',
        'interactionCreate',
        'invalidated',
        'invalidRequestWarning',
        'inviteCreate',
        'inviteDelete',
        "message",
        'messageCreate',
        'messageDelete',
        'messageDeleteBulk',
        'messageReactionAdd',
        'messageReactionRemove',
        'messageReactionRemoveAll',
        'messageReactionRemoveEmoji',
        'messageUpdate',
        'presenceUpdate',
        'rateLimit',
        'ready',
        'reconnecting',
        'disconnect',
        'roleCreate',
        'roleDelete',
        'roleUpdate',
        'shardDisconnect',
        "shardError",
        'shardReady',
        "shardReconnecting",
        'shardResume',
        'stageInstanceCreate',
        'stageInstanceDelete',
        'stageInstanceUpdate',
        'stickerCreate',
        'stickerDelete',
        "stickerUpdate",
        "threadCreate",
        "threadDelete",
        "threadListSync",
        "threadMembersUpdate",
        "threadMemberUpdate",
        "threadUpdate",
        "typingStart",
        'userUpdate',
        "voiceStateUpdate",
        "warn",
        "webhookUpdate",
    ]
}

/**
 * @INFO
 * Bot Coded by Zedro#2742 | https://discord.gg/milanio
 * @INFO
 * Work for Milanio Development | https://discord.gg/milanio
 * @INFO
 * Please Mention Us Milanio Development, When Using This Code!
 * @INFO
 */